apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  selector:
    matchLabels:
      app: processor
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: processor
        image: james95meyer/processor:v6
